export { default as charactersDataSlice } from './characters/charactersDataSlice';
export { default as charactersDetailsSlice } from './characters/charactersDetailsSlice';
export { default as filmsDataSlice } from './films/filmsDataSlice';
export { default as filmsDetailsSlice } from './films/filmsDetailsSlice';
export * from './index';
export { default as planetsDataSlice } from './planets/planetsDataSlice';
export { default as planetsDetailsSlice } from './planets/planetsDetailsSlice';
export { default as speciesDataSlice } from './species/speciesDataSlice';
export { default as speciesDetailsSlice } from './species/speciesDetailsSlice';
export { default as starShipsDataSlice } from './starShips/starShipsDataSlice';
export { default as starShipsDetailsSlice } from './starShips/starShipsDetailsSlice';
export { default as vehiclesDataSlice } from './vehicles/vehiclesDataSlice';
export { default as vehiclesDetailsSlice } from './vehicles/vehiclesDetailsSlice';
